### PR TITLE
Ensmallen version check

### LINKED ISSUE #117: Error building the mnist_cnn and mnist_simple example
When i try to build the mnist_cnn.cpp and the mnist_simple.cpp i get the following error which is same for both files.
the version of mlpack i have is: 3.2.2-3
```
mnist_cnn.cpp: In function ‘int main()’:
mnist_cnn.cpp:189:20: error: no matching function for call to ‘ens::EarlyStopAtMinLoss::EarlyStopAtMinLoss(main()::<lambda(const mat&)>)’
  189 |                   }));
      |                    ^
In file included from /usr/include/ensmallen.hpp:67,
                 from /usr/include/mlpack/methods/ann/ffn.hpp:33,
                 from mnist_cnn.cpp:20:
/usr/include/ensmallen_bits/callbacks/early_stop_at_min_loss.hpp:31:3: note: candidate: ‘ens::EarlyStopAtMinLoss::EarlyStopAtMinLoss(size_t)’
   31 |   EarlyStopAtMinLoss(const size_t patienceIn = 10) :
      |   ^~~~~~~~~~~~~~~~~~
/usr/include/ensmallen_bits/callbacks/early_stop_at_min_loss.hpp:31:35: note:   no known conversion for argument 1 from ‘main()::<lambda(const mat&)>’ to ‘size_t’ {aka ‘long unsigned int’}
   31 |   EarlyStopAtMinLoss(const size_t patienceIn = 10) :
      |                      ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/usr/include/ensmallen_bits/callbacks/early_stop_at_min_loss.hpp:21:7: note: candidate: ‘constexpr ens::EarlyStopAtMinLoss::EarlyStopAtMinLoss(const ens::EarlyStopAtMinLoss&)’
   21 | class EarlyStopAtMinLoss
      |       ^~~~~~~~~~~~~~~~~~
/usr/include/ensmallen_bits/callbacks/early_stop_at_min_loss.hpp:21:7: note:   no known conversion for argument 1 from ‘main()::<lambda(const mat&)>’ to ‘const ens::EarlyStopAtMinLoss&’
/usr/include/ensmallen_bits/callbacks/early_stop_at_min_loss.hpp:21:7: note: candidate: ‘constexpr ens::EarlyStopAtMinLoss::EarlyStopAtMinLoss(ens::EarlyStopAtMinLoss&&)’
/usr/include/ensmallen_bits/callbacks/early_stop_at_min_loss.hpp:21:7: note:   no known conversion for argument 1 from ‘main()::<lambda(const mat&)>’ to ‘ens::EarlyStopAtMinLoss&&’
make: *** [<builtin>: mnist_cnn.o] Error 1
```

### PR DESCRIPTION
**Pull request by Aakash-kaushik**
Added ensmallen version check and corrected some data file names. 
Closes #117

### CODE REVIEW

File: mnist_batch_norm/mnist_batch_norm.cpp [hunk 1]
```diff
@@ -24,6 +24,10 @@
 #include <ensmallen.hpp>
 #include <ensmallen_bits/callbacks/callbacks.hpp>
 
+#if ((ENS_VERSION_MAJOR < 2) || (ENS_VERSION_MINOR < 13))
```
Comment (zoq) [inline mnist_batch_norm/mnist_batch_norm.cpp:27]: We should use `&&` here right?

Comment (Aakash-kaushik) [reply mnist_batch_norm/mnist_batch_norm.cpp:27]: So i installed a version of ensmallen less than 2.14 so i can actually see the #if working but with `&&` it wasn't producing any errors.

Comment (zoq) [reply mnist_batch_norm/mnist_batch_norm.cpp:27]: That is strange, if I didn't miss anything, the current construct will also raise an error if the version is 3.10.

Comment (Aakash-kaushik) [reply mnist_batch_norm/mnist_batch_norm.cpp:27]: Yes i think that will be the case, but i turned up with this solution because `&&` wasn't working. Also just a small implementation note on what i did.
`
#if (major version check && minor version check)
`
This is what i did and do you think 
`
#if (minor version check && major version check)
`
Will work as expected ?

Comment (Aakash-kaushik) [reply mnist_batch_norm/mnist_batch_norm.cpp:27]: I think a check similar to [this](https://github.com/mlpack/ensmallen/blob/a37f49cb9b6e003f92abb100b9758779545d02b3/include/ensmallen.hpp#L32) might work, i will check and push it in the morning.

Comment (zoq) [reply mnist_batch_norm/mnist_batch_norm.cpp:27]: Yes, that should solve the issue.

Comment (Aakash-kaushik) [reply mnist_batch_norm/mnist_batch_norm.cpp]: @zoq fixed it and verified it by manually changing the version of ensmallen to `3.10`. Doesn't produces a error for that.

**Review by zoq — APPROVED** [review]
Thanks for putting this together, no further comments from my side.

**Comment by Aakash-kaushik** [comment]
> Thanks for putting this together, no further comments from my side.

Thanks for reviewing it. :D

**Comment by zoq** [comment]
Thanks for the contribution.
